services:
  - type: web
    name: admin-panel-api
    env: node
    buildCommand: npm install
    startCommand: node server/server.js
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 4000
